runtime: python39
handlers:
  - url: /api/.*
    script: auto

  - url: /
    static_files: web/out/index.html
    upload: web/out/index.html

  - url: /(register|login|user)
    static_files: web/out/\1.html
    upload: web/out/(.*)\.html

  - url: /(.*)
    static_files: web/out/\1
    upload: web/out/(.*)
